=== VulcaN-Study/Supplementary-Material/vulcan/interface/schema-validator/report-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "advisory": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "cwe": {
                    "type": "string"
                }
            },
            "required": [
                "id",
                "cwe"
            ],
            "additionalProperties": false
        },
        "correct_cwe": {
            "type": "string",
            "additionalProperties": false
        },
        "correct_package_link": {
            "type": "string",
            "additionalProperties": false
        },
        "vulnerability": {
            "type": "object",
            "properties": {
                "vulnerability_location": {
                    "type": "array",
                    "items": [
                        {
                            "type": "object",
                            "properties": {
                                "source": {
                                    "type": "object",
                                    "properties": {
                                        "file": {
                                            "type": "string"
                                        },
                                        "lineno": {
                                            "type": "integer"
                                        },
                                        "code": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "file",
                                        "lineno",
                                        "code"
                                    ],
                                    "additionalProperties": false
                                },
                                "sink": {
                                    "type": "object",
                                    "properties": {
                                        "file": {
                                            "type": "string"
                                        },
                                        "lineno": {
                                            "type": "integer"
                                        },
                                        "code": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "file",
                                        "lineno",
                                        "code"
                                    ],
                                    "additionalProperties": false
                                },
                                "block": {
                                    "type": "object",
                                    "properties": {
                                        "file": {
                                            "type": "string"
                                        },
                                        "start_lineno": {
                                            "type": "integer"
                                        },
                                        "end_lineno": {
                                            "type": "integer"
                                        },
                                        "code": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "file",
                                        "start_lineno",
                                        "end_lineno",
                                        "code"
                                    ],
                                    "additionalProperties": false
                                }
                            }
                        }
                    ]
                },
                "fail_reason": {
                    "type": "string"
                }
            },
            "required": [
                "fail_reason"
            ],
            "additionalProperties": false
        },
        "poc": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "url": {
                            "type": "string"
                        },
                        "code": {
                            "type": "string"
                        },
                        "file_path": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false
                }
            ],
            "additionalProperties": false
        },
        "patch": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "url": {
                            "type": "string"
                        },
                        "file_path": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false
                }
            ],
            "additionalProperties": false
        },
        "tools": {
            "type": "object",
            "properties": {
                "codeql": {
                    "type": "object",
                    "properties": {
                        "score": {
                            "type": "string",
                            "enum": [
                                "A",
                                "B",
                                "C",
                                "D",
                                "E"
                            ]
                        }
                    },
                    "required": [
                        "score"
                    ],
                    "additionalProperties": false
                },
                "njsscan": {
                    "type": "object",
                    "properties": {
                        "score": {
                            "type": "string",
                            "enum": [
                                "A",
                                "B",
                                "C",
                                "D",
                                "E"
                            ]
                        }
                    },
                    "required": [
                        "score"
                    ],
                    "additionalProperties": false
                },
                "graudit": {
                    "type": "object",
                    "properties": {
                        "score": {
                            "type": "string",
                            "enum": [
                                "A",
                                "B",
                                "C",
                                "D",
                                "E"
                            ]
                        }
                    },
                    "required": [
                        "score"
                    ],
                    "additionalProperties": false
                },
                "insidersec": {
                    "type": "object",
                    "properties": {
                        "score": {
                            "type": "string",
                            "enum": [
                                "A",
                                "B",
                                "C",
                                "D",
                                "E"
                            ]
                        }
                    },
                    "required": [
                        "score"
                    ],
                    "additionalProperties": false
                },
                "eslint": {
                    "type": "object",
                    "properties": {
                        "score": {
                            "type": "string",
                            "enum": [
                                "A",
                                "B",
                                "C",
                                "D",
                                "E"
                            ]
                        }
                    },
                    "required": [
                        "score"
                    ],
                    "additionalProperties": false
                },
                "appinspector": {
                    "type": "object",
                    "properties": {
                        "score": {
                            "type": "string",
                            "enum": [
                                "A",
                                "B",
                                "C",
                                "D",
                                "E"
                            ]
                        }
                    },
                    "required": [
                        "score"
                    ],
                    "additionalProperties": false
                },
                "msdevskim": {
                    "type": "object",
                    "properties": {
                        "score": {
                            "type": "string",
                            "enum": [
                                "A",
                                "B",
                                "C",
                                "D",
                                "E"
                            ]
                        }
                    },
                    "required": [
                        "score"
                    ],
                    "additionalProperties": false
                },
                "drek": {
                    "type": "object",
                    "properties": {
                        "score": {
                            "type": "string",
                            "enum": [
                                "A",
                                "B",
                                "C",
                                "D",
                                "E"
                            ]
                        }
                    },
                    "required": [
                        "score"
                    ],
                    "additionalProperties": false
                },
                "mosca": {
                    "type": "object",
                    "properties": {
                        "score": {
                            "type": "string",
                            "enum": [
                                "A",
                                "B",
                                "C",
                                "D",
                                "E"
                            ]
                        }
                    },
                    "required": [
                        "score"
                    ],
                    "additionalProperties": false
                }
            },
            "required": [
                "codeql",
                "njsscan",
                "graudit",
                "insidersec",
                "eslint",
                "appinspector",
                "msdevskim",
                "drek",
                "mosca"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "advisory",
        "correct_cwe",
        "correct_package_link",
        "vulnerability",
        "tools"
    ],
    "additionalProperties": false
}

=== VulcaN-Study/Supplementary-Material/vulcan/interface/schema-validator/examples/report-example-3.json
{
    "advisory": {
        "id": 10002,
        "cwe": "CWE-94"
    },
    "correct_cwe": "CWE-78",
    "correct_package_link": "https://registry.npmjs.org/pack/-/pack-0.1.22.tgz",
    "vulnerability": {
        "vulnerability_location": [
            {
                "block": {
                    "file": "index.js",
                    "start_lineno": 11,
                    "end_lineno": 13,
                    "code": "function (req, res) {"
                }
            }
        ],
        "fail_reason": ""
    },
    "poc": [
        {
            "url": "exploitdb.com/package/poc-example"
        }
    ],
    "patch": [
        {
            "url": "github.com/package/commit/commitid"
        }
    ],
    "tools": {
        "codeql": {
            "score": "C"
        },
        "njsscan": {
            "score": "C"
        },
        "graudit": {
            "score": "B"
        },
        "insidersec": {
            "score": "C"
        },
        "eslint": {
            "score": "D"
        },
        "appinspector": {
            "score": "C"
        },
        "msdevskim": {
            "score": "C"
        },
        "drek": {
            "score": "D"
        },
        "mosca": {
            "score": "B"
        }
    }
}

=== VulcaN-Study/Supplementary-Material/vulcan/interface/schema-validator/examples/report-example-2.json
{
    "advisory": {
        "id": 10001,
        "cwe": "CWE-94"
    },
    "correct_cwe": "CWE-78",
    "correct_package_link": "https://registry.npmjs.org/pack/-/pack-0.1.22.tgz",
    "vulnerability": {
        "fail_reason": "Insufficient information in Overview, External References or Tool Reports. Could not execute vulnerable code to test vulnerability because of ..."
    },
    "poc": [
        {
            "url": "exploitdb.com/package/poc-example"
        }
    ],
    "patch": [
        {
            "url": "github.com/package/commit/commitid"
        }
    ],
    "tools": {
        "codeql": {
            "score": "D"
        },
        "njsscan": {
            "score": "D"
        },
        "graudit": {
            "score": "D"
        },
        "insidersec": {
            "score": "C"
        },
        "eslint": {
            "score": "C"
        },
        "appinspector": {
            "score": "D"
        },
        "msdevskim": {
            "score": "C"
        },
        "drek": {
            "score": "D"
        },
        "mosca": {
            "score": "C"
        }
    }
}

=== VulcaN-Study/Supplementary-Material/vulcan/interface/schema-validator/examples/report-example-1.json
{
    "advisory": {
        "id": 10000,
        "cwe": "CWE-94"
    },
    "correct_cwe": "CWE-78",
    "correct_package_link": "https://registry.npmjs.org/pack/-/pack-0.1.22.tgz",
    "vulnerability": {
        "vulnerability_location": [
            {
                "source": {
                    "file": "index.js",
                    "lineno": 11,
                    "code": "function (req, res) {"
                },
                "sink": {
                    "file": "index.js",
                    "lineno": 20,
                    "code": "exec(req.command);"
                }
            }
        ],
        "fail_reason": ""
    },
    "poc": [
        {
            "url": "exploitdb.com/package/poc-example"
        }
    ],
    "patch": [
        {
            "url": "github.com/package/commit/commitid"
        }
    ],
    "tools": {
        "codeql": {
            "score": "C"
        },
        "njsscan": {
            "score": "C"
        },
        "graudit": {
            "score": "B"
        },
        "insidersec": {
            "score": "C"
        },
        "eslint": {
            "score": "D"
        },
        "appinspector": {
            "score": "C"
        },
        "msdevskim": {
            "score": "C"
        },
        "drek": {
            "score": "D"
        },
        "mosca": {
            "score": "B"
        }
    }
}
